# Generated by Django 5.1.1 on 2025-02-20 05:18

import datetime
import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ApiPlatform', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='referral',
            name='referral_expiry_date',
            field=models.DateField(blank=True, default=datetime.date(2025, 4, 21), null=True),
        ),
        migrations.CreateModel(
            name='ReplyHelpFull',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('is_liked', models.BooleanField(default=False)),
                ('reply_id', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reply_help_full', to='ApiPlatform.adminreply')),
                ('user_id', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reply_help_full', to='ApiPlatform.user')),
            ],
            options={
                'verbose_name_plural': 'Reply Help Full',
                'ordering': ['is_liked'],
            },
        ),
        migrations.AddField(
            model_name='adminreply',
            name='reply_help_full_id',
            field=models.ManyToManyField(blank=True, related_name='admin_replies', to='ApiPlatform.replyhelpfull'),
        ),
        migrations.CreateModel(
            name='ReplyNotHelpFull',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('is_liked', models.BooleanField(default=False)),
                ('reply_id', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reply_not_help_full', to='ApiPlatform.adminreply')),
                ('user_id', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reply_not_help_full', to='ApiPlatform.user')),
            ],
            options={
                'verbose_name_plural': 'Reply Not Help Full',
                'ordering': ['is_liked'],
            },
        ),
        migrations.AddField(
            model_name='adminreply',
            name='reply_not_help_full_id',
            field=models.ManyToManyField(blank=True, related_name='admin_replies', to='ApiPlatform.replynothelpfull'),
        ),
    ]
