# Generated by Django 5.1.1 on 2025-03-03 05:40

import datetime
import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("ApiPlatform", "0004_game_is_promotional"),
    ]

    operations = [
        migrations.AlterField(
            model_name="referral",
            name="referral_expiry_date",
            field=models.DateField(
                blank=True, default=datetime.date(2025, 5, 2), null=True
            ),
        ),
        migrations.CreateModel(
            name="Bonus",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("amount", models.IntegerField()),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "user_id",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="bonuses",
                        to="ApiPlatform.user",
                    ),
                ),
            ],
            options={
                "verbose_name_plural": "Bonuses",
                "ordering": ["created_at"],
            },
        ),
    ]
