# Generated by Django 5.1.1 on 2025-03-04 08:08

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("ApiPlatform", "0005_alter_referral_referral_expiry_date_bonus"),
    ]

    operations = [
        migrations.AlterField(
            model_name="referral",
            name="referral_expiry_date",
            field=models.DateField(
                blank=True, default=datetime.date(2025, 5, 3), null=True
            ),
        ),
    ]
