# Generated by Django 5.1.1 on 2025-03-04 08:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("ApiPlatform", "0006_alter_referral_referral_expiry_date"),
    ]

    operations = [
        migrations.AlterField(
            model_name="notification",
            name="notification_type",
            field=models.CharField(
                choices=[
                    ("Game Creation", "Game Creation"),
                    ("Game Deletion", "Game Deletion"),
                    ("Game Update", "Game Update"),
                    ("Game Review", "Game Review"),
                    ("Game Rating", "Game Rating"),
                    ("Game Play", "Game Play"),
                    ("Game Transaction", "Game Transaction"),
                    ("Payment", "Payment"),
                    ("Bonus", "Bonus"),
                    ("Subscription", "Subscription"),
                    ("Promo Code", "Promo Code"),
                    ("Referral", "Referral"),
                    ("Global Chat", "Global Chat"),
                    ("Agent Chat", "Agent Chat"),
                    ("Admin Reply", "Admin Reply"),
                    ("Review Help Full", "Review Help Full"),
                    ("Review Not Help Full", "Review Not Help Full"),
                    ("Reply Help Full", "Reply Help Full"),
                    ("Reply Not Help Full", "Reply Not Help Full"),
                    ("Message", "Message"),
                    ("Message Conversation", "Message Conversation"),
                    ("Player", "Player"),
                    ("Player Create", "Player Create"),
                    ("Player Delete", "Player Delete"),
                    ("Player Update", "Player Update"),
                    ("Player Review", "Player Review"),
                    ("Player Rating", "Player Rating"),
                    ("Player Play", "Player Play"),
                    ("Player Transaction", "Player Transaction"),
                    ("Player Payment", "Player Payment"),
                    ("Player Bonus", "Player Bonus"),
                    ("Player Subscription", "Player Subscription"),
                    ("Player Promo Code", "Player Promo Code"),
                    ("Player Referral", "Player Referral"),
                    ("Player Global Chat", "Player Global Chat"),
                    ("Player Agent Chat", "Player Agent Chat"),
                    ("Player Admin Reply", "Player Admin Reply"),
                    ("Player Review Help Full", "Player Review Help Full"),
                    ("Player Review Not Help Full", "Player Review Not Help Full"),
                    ("Player Reply Help Full", "Player Reply Help Full"),
                    ("Player Reply Not Help Full", "Player Reply Not Help Full"),
                    ("Player Message", "Player Message"),
                    ("Player Message Conversation", "Player Message Conversation"),
                    ("Player Notification", "Player Notification"),
                    ("Player Notification Read", "Player Notification Read"),
                ],
                max_length=50,
            ),
        ),
    ]
