# Generated by Django 5.1.1 on 2025-03-04 11:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("ApiPlatform", "0008_notification_is_read"),
    ]

    operations = [
        migrations.AlterField(
            model_name="notification",
            name="notification_type",
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
