# Generated by Django 5.1.1 on 2025-03-04 12:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("ApiPlatform", "0009_alter_notification_notification_type"),
    ]

    operations = [
        migrations.AlterField(
            model_name="payment",
            name="coin",
            field=models.CharField(
                blank=True,
                choices=[
                    ("BTC", "Bitcoin"),
                    ("ETH", "Ethereum"),
                    ("USDT", "Tether"),
                    ("LTC", "Litecoin"),
                ],
                max_length=50,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="payment",
            name="network",
            field=models.CharField(
                blank=True,
                choices=[
                    ("BTC", [("Bitcoin", "Bitcoin"), ("Lightening", "Lightening")]),
                    ("ETH", [("ERC20", "ERC20"), ("BEP20", "BEP20")]),
                    ("USDT", [("TRC20", "TRC20"), ("ERC20", "ERC20")]),
                    ("LTC", [("Lightcoin", "Lightcoin")]),
                ],
                max_length=50,
                null=True,
            ),
        ),
    ]
