# Generated by Django 5.1.1 on 2025-03-04 12:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("ApiPlatform", "0010_alter_payment_coin_alter_payment_network"),
    ]

    operations = [
        migrations.RenameField(
            model_name="payment",
            old_name="screenshot",
            new_name="upload_proof",
        ),
        migrations.AlterField(
            model_name="payment",
            name="status",
            field=models.CharField(
                choices=[
                    ("Pending", "Pending"),
                    ("Approved", "Approved"),
                    ("Cancelled", "Cancelled"),
                ],
                default="Pending",
                max_length=50,
            ),
        ),
    ]
