# Generated by Django 5.1.1 on 2025-03-04 20:26

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("ApiPlatform", "0011_rename_screenshot_payment_upload_proof_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="referral",
            name="referral_expiry_date",
            field=models.DateField(
                blank=True, default=datetime.date(2025, 5, 4), null=True
            ),
        ),
    ]
